Update kafka.go to fix typo
zilliztech/milvus-operator pull request #72
Opened 2024-01-26 04:30 UTC by SahilDevgon

2024-01-26 09:30 UTC, haorenfsa requested changes

2024-01-26 09:30 UTC, haorenfsa commented on pkg/external/kafka.go
> +		# Fixing typo in err meesage
this comment is not necessary

2024-01-26 09:32 UTC, haorenfsa commented
Hi @SahilDevgon, before we can merge your patch, please sign off your commits. check this doc for detail: https://github.com/apps/dco

2024-01-26 11:41 UTC, SahilDevgon commented on pkg/external/kafka.go
> +		# Fixing typo in err meesage
comment is removed

2024-01-28 15:03 UTC, SahilDevgon reviewed
Additional comment is removed as requested

2024-01-29 02:20 UTC, haorenfsa commented
about CI failure: the v2.3.6 milvus image has critical bugs, so they deleted this tag to avoid being used.

2024-01-29 02:23 UTC, haorenfsa requested changes

2024-01-29 02:23 UTC, haorenfsa commented on docs/administration/manage-dependencies/message-storage.md
> +      SecurityProtocol: PLAINTEXT
Another catch XD, but the fields in `spec.config` are capital sensitive, see:
https://github.com/milvus-io/milvus/blob/v2.3.7/pkg/util/paramtable/service_param.go#L688

2024-01-29 03:04 UTC, SahilDevgon reviewed
Fixed the case-sensitivity issue

2024-01-29 03:04 UTC, sahildevgon commented on docs/administration/manage-dependencies/message-storage.md
> +      SecurityProtocol: PLAINTEXT
Yes, updated the same.

2024-01-29 03:37 UTC, haorenfsa approved these changes

2024-01-29 05:38 UTC, merged